@baseAddress = http://localhost:5117
@givenId = 08dd456f-879d-152a-50eb-f6e65c700000
GET {{baseAddress}}/api/categories
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 2"
}
###
GET {{baseAddress}}/api/categories/{{givenId}}
Accept: application/jso

###
