@baseAddress = http://localhost:5117
@givenId = 08dd456f-879d-152a-50eb-f6e65c700000
@courseId = 08dd464c-e198-57b7-50eb-f6e65c700000
GET {{baseAddress}}/api/v1.0/categories
Accept: application/json
###
POST {{baseAddress}}/api/v1.0/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 2"
}
###
GET {{baseAddress}}/api/v1.0/categories{{givenId}}
Accept: application/json

###

POST {{baseAddress}}/api/v1.2/courses
Accept: application/json
Content-Type: application/json
{
  "name": "Course 1",
  "description": "Description 1",
  "price": 100,
  "categoryid": {{givenId}},
  "imageUrl": "http://example.com/picture.jpg"
}
###
PUT {{baseAddress}}/api/v1.2/courses/{{courseId}}
Accept: application/json
Content-Type: application/json
{
  "name": "Course 1 Updated",
  "description": "Description 1 Updated",
  "price": 200,
  "categoryid": {{givenId}},
  "imageUrl": "http://example.com/picture1.jpg"
}
###
DELETE {{baseAddress}}/api/v1.2/courses/{{courseId}}
Accept: application/json
###
GET {{baseAddress}}/api/v1.2/courses
Accept: application/json
###
GET {{baseAddress}}/api/v1.2/courses/{{courseId}}
Accept: application/json
###
